kind: Service
apiVersion: v1
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
